title: "Ben West"
baseURL: "https://m0nkeyfl0wer.github.io/benwest-blog"
theme: "PaperMod"
defaultContentLanguage: "en"

pagination:
  pagerSize: 10

taxonomies:
  category: categories
  tag: tags
  series: series

params:
  env: production
  description: "Strategy, media and democracy."
  defaultTheme: dark
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  ShowToc: true

  assets:
    disableFingerprinting: true
    customCSS:
      - css/custom.css

  profileMode:
    enabled: true
    title: "Ben West"
    subtitle: "Writer, strategist, and recovering campaigner."
    imageUrl: "profile.jpg"
    imageTitle: "Ben West"
    buttons:
      - name: Posts
        url: "/posts"
      - name: Bluesky
        url: "https://bsky.app/profile/benwest.bsky.social"

markup:
  highlight:
    noClasses: false
