baseURL: "https://m0nkeyfl0wer.github.io/"
title: "Ben West"
theme: "hugo-theme-stack"
defaultContentLanguage: "en"
enableRobotsTXT: true

params:
  author:
    name: "Ben West"
    avatar:
      enabled: true
      local: true
      src: "images/avatar.png"
    links:
      - icon: bsky
        title: "Bluesky"
        url: "https://bsky.app/profile/m0nkeyfl0wer.bsky.social"
