title: "Ben West"
baseURL: "https://m0nkeyfl0wer.github.io/benwest-blog/"
theme: "PaperMod"
defaultContentLanguage: "en"

pagination:
  pagerSize: 5

taxonomies:
  category: categories
  tag: tags
  series: series

params:
  author: "Ben West"
  description: "Writing, research, and anti-royalist ramblings."
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  ShowToc: true
  TocOpen: true
  comments: false
  defaultTheme: "dark"
  disableThemeToggle: false


  socialIcons:
    - name: "Bluesky"
      url: "https://bsky.app/profile/benwest.bsky.social"
    - name: "GitHub"
      url: "https://github.com/M0nkeyFl0wer"
